#!/bin/env/bash
# +++++++++++++++ ZSH +++++++++++++++++++++

export CUSTOM_CONFIG_SOURCE=~/dotfiles
export CUSTOM_CONFIG_HOME=~/.config
export CUSTOM_CACHE_HOME=~/.cache

## Path to your oh-my-zsh installation.
export ZSH="$CUSTOM_CONFIG_HOME/oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"

## If you come from bash you might have to change your $PATH.
export PATH=/usr/local/bin:$PATH
export PATH=/opt/local/bin:/opt/local/sbin/:$PATH

# +++++++++++++++ /ZSH +++++++++++++++++++++

# Get local config options
# shellcheck disable=SC1090
source "$CUSTOM_CONFIG_SOURCE/profile/.profile"

# OH-MY_ZSH Theme config
# shellcheck disable=SC2034
{
  ZSH_THEME="spaceship"
  SPACESHIP_PROMPT_ADD_NEWLINE="true"
  SPACESHIP_CHAR_SYMBOL="\uf0e7"
  SPACESHIP_CHAR_PREFIX="\uf296"
  SPACESHIP_CHAR_SUFFIX=(" ")
  SPACESHIP_CHAR_COLOR_SUCCESS="yellow"
  SPACESHIP_PROMPT_DEFAULT_PREFIX="$USER"
  SPACESHIP_PROMPT_FIRST_PREFIX_SHOW="true"
  SPACESHIP_USER_SHOW="true"
}
# ZSH Plugins
# shellcheck disable=SC2034
plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  docker
)

# Auto configure OH MY ZSH
# shellcheck disable=SC1090
[ -f "$ZSH/oh-my-zsh.sh" ] && source "$ZSH/oh-my-zsh.sh"

# If using MAC, source iTerm shell integration
# IS_MAC is set in $HOME/.local_env/.profile
if [ "$IS_MAC" = true ]; then
    # shellcheck disable=SC1090
    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

function mon_left_only () {
    xrandr --output VGA1 --off --output eDP1 --off --output HDMI1 --primary --auto
}


function mon_right_only () {
    xrandr --output HDMI1 --off --output eDP1 --off --output VGA1 --primary --auto
}

function mon_laptop () {
    xrandr --output HDMI1 --off --output VGA1 --off --output eDP1 --primary --auto
}

function mon_both () {
    xrandr --output eDP1 --off --output HDMI1 --primary --auto --output VGA1 --off 
    xrandr --output VGA1 --right-of HDMI1 --auto 
}
